#!/usr/bin/env python3

from sys import argv, exit
from src.check_error import check_error
from src.matrice_operand import (
    get_matrice_identite,
    divide_matrix,
    multiplication_matrix,
    adding_matrix,
    mul_matrix,
)
from src.sinus import sinush, sinuss
from src.cosinus import cossinus, cossinush
from src.exponatial import print_matrice, exponantiel


def display_usage() -> int:
    print("USAGE\n    ./108trigo fun a0 a1 a2 ...\n")
    print("DESCRIPTION\n    fun    function to be applied, among at least", end="")
    print(' "EXP", "COS", "SIN", "COSH"\n\t   and "SINH"')
    print("    ai     coeficients of the matrix")
    return 0


def begin(argv: list[str]) -> int:
    dico = {
        "EXP": exponantiel,
        "COS": cossinus,
        "SIN": sinuss,
        "SINH": sinush,
        "COSH": cossinush,
    }
    result: list[list[float]] = dico[argv[1]](argv)
    print_matrice(result)
    return 0


def main() -> int:
    if "-h" in argv:
        display_usage()
        return 0
    if check_error(argv) == 84:
        return 84
    return begin(argv)


if __name__ == "__main__":
    exit(main())
